### ISSUE TITLE
Cannot prove assertion using unfolding inside forall

### ISSUE THREAD

**Issue by bobismijnnaam** [viperproject/silicon#482]
We ran into the following code today:

```
field x: Int;

predicate state(this: Ref) {
    this != null && acc(this.x, 1/1) && this.x > 0
}

method foo(cells: Seq[Ref]) 
requires forall i: Int :: 0 <= i && i < |cells| ==> state(cells[i])
{
    assert (forall i: Int :: 0 <= i && i < |cells| ==> (unfolding state(cells[i]) in cells[i].x > 0))
}
```

This is a reduced example from VerCors. We would expect this to verify, but instead the assert fails to verify.

When we try to "unroll" the forall by writing a for loop that unfolds each predicate and assert that `cells[i].x > 0` it works fine. We also added a trigger to the requires (something like `{ state(cells[i]) }`) but that didn't seem to make a difference.

Are we misunderstanding how `unfolding` is supposed to work, using it in an invalid context, or is there something else going wrong? It seems to be very much related to #228, but we are unsure how to apply the workaround mentioned in the issue here (or in our frontend, for that matter).

**Comment by mschwerhoff** [comment]
To my surprise, the problem does not seem to occur with Silicon revision 4bab8b07 (issue #228 appears to have been fixed as well).

I'm surprised because I think I never manages to overcome the root problem (the partial heap obtained from the unfolding is defined under the quantifier, but occurs in the trigger, and thus "protects" its own definition). I did experiment with various workarounds, maybe one of those saves the day here.

Please try again with the latest Silicon version and let me know which result you get.

**Comment by mschwerhoff** [comment]
A brief look at the resulting SMT code confirms my suspicion: the root problem remains, but because Viper picks `{cells[i]}` as the trigger, which is heap-independent, the problem doesn't strike here. Changing the trigger to `{cells[i].x}`, which depends on the partial heap obtained from the unfolding, makes the assertion fail again.

If it's OK with you, please close the issue as a duplicate of #228.

**Comment by bobismijnnaam** [comment]
It's clear where the problem is coming from, so that is fine with me. Thanks for the thorough explanation.
