### ISSUE TITLE
Contradictions between package block and application site

### ISSUE THREAD

**Issue by fpoli** [viperproject/silicon#485]
Is it possible to assert `false` after the `apply` in the following program?

```
field val: Bool

method first(x: Ref)
    requires acc(x.val)
    ensures acc(x.val)
    ensures acc(x.val) --* acc(x.val)
{
    package acc(x.val) --* acc(x.val) {
        assume x.val == true
    }
}

method second(x: Ref)
    requires acc(x.val)
{
    first(x)
    x.val := false
    apply acc(x.val) --* acc(x.val)
    // Is it possible to observe that we assumed `x.val == true` in the package block?
}
```

**Comment by mschwerhoff** [comment]
I'm not sure what the exact question here is. Do you think `false` should be assertable after the `apply`?

**Comment by fpoli** [comment]
> I'm not sure what the exact question here is. Do you think `false` should be assertable after the `apply`?

Exactly. I wonder whether I'm introducing an unsoundness in a model by doing so.

**Comment by mschwerhoff** [comment]
Whether the `assume` is justified or not depends on your concrete use case, but in general, it is an additional assumption that might contradict the actual program state. Here, technicalities such as our treatment of wands as opaque entities, incomplete wand snapshots, and package/apply in different scopes, apparently prevent you from proving false.

Consider the stronger wand `acc(x.val) --* acc(x.val) && x.val`, which you can package thanks to the additional assume. Semantically, the wand holds in a state where `acc(x.f) && x.f == false` only because you cannot add a compatible LHS heap to the current state (since that would mean too many permissions). I.e. the wand holds vacuously.

If you change your program to package this wand, then you can assert false after applying it, but only in Carbon. Silicon appears to be incomplete here. That's in general the case with wands: Carbon is more complete, sometimes even "too complete". I don't remember the concrete problems with had here in Carbon, Gaurav can probably give you details.

**Comment by fpoli** [comment]
Thank you. So, the final message is that assuming things in the package statement, knowing that they might contradict the actual program state, is *bad practice* because it's only due to special technicalities that the tool does not prove false. In the case of packaging magic wands, this seems particularly fragile.
