### ISSUE TITLE
Method Precondition Not Assertable

### ISSUE THREAD

**Issue by ckamueller** [viperproject/silicon#493]
Silicon fails to assert a precondition to a method:

```
field val: Int

predicate p(a: Ref)
{
    acc(a.val)
}

function foo(set: Set[Ref]): Int
    requires forall a: Ref :: { p(a) } a in set ==> p(a)

method meth(set: Set[Ref])
    requires (forall a: Ref :: { p(a) } a in set ==> p(a)) &&
             foo(set) == 0
{
    // okay with Carbon, "Assertion foo(set) == 0 might not hold" with Silicon
    assert foo(set) == 0
}
```

This appears to be related to the occurrence of predicate `p` and set `set` in the same precondition to function `foo` - removing/replacing either allowes Silicion to verify the code.

Any workaround would be highly appreciated.

**Comment by mschwerhoff** [comment]
Resolved with pull request #497 and commit dea3bfd.

Thanks for reporting this, @ckamueller. Turned out that framing for QPs over predicates and wands was severely broken and basically did not work at all. This wasn't noticed earlier because there was no test that combined QPs over predicates (or wands) with abstract functions.
