### ISSUE TITLE
Insufficient Permissions in Quantified Implication

### ISSUE THREAD

**Issue by ArquintL** [viperproject/silicon#500]
The following Viper code is successfully verified by Carbon but Silicon reports that the precondition of `get_next_t` might not hold because of insufficient permissions to `event(t)`:

```
function P_i1_trigger(a: Int): Bool
predicate P_i1(t: Int) {
    forall a: Int :: 
        { P_i1_trigger(a) }
        a == 5 ==> event(t) && P_i1(get_next_t(t))
}

predicate event(t: Int)
function get_next_t(t: Int): Int
    requires event(t)
```

Is there a workaround (while keeping the implication and the quantifier)?

**Comment by mschwerhoff** [comment]
First observation: seems to be some kind of triggering problem:

```
function P_i1_trigger(a: Int): Bool

predicate P_i1(t: Int) {
    forall a: Int :: 
      // { P_i1_trigger(a) } // fails
      { event(t, a) } // succeeds
      a == 5 ==> event(t, a) && P_i1(get_next_t(t, a))
}

predicate event(t: Int, a: Int)

function get_next_t(t: Int, a: Int): Int
    requires event(t, a)
```

**Comment by ArquintL** [comment]
Awesome! Yes, using the `event` predicate as trigger fixes the issue and even saves me from writing this artificial trigger function

**Comment by mschwerhoff** [comment]
Nice to hear that the workaround is even better than the originally intended approach :-) I'll nevertheless look into the original problem eventually.

**Comment by marcoeilers** [comment]
For me, the original example does not verify with Silicon or Carbon, and I would say that is an expected result of the way Viper desugars quantified permissions.
```
forall a: Int :: { P_i1_trigger(a) } a == 5 ==> event(t) && P_i1(get_next_t(t))
```
should, afaik, be desugared to 
```
forall a: Int :: { P_i1_trigger(a) } a == 5 ==> event(t) && 
forall a: Int :: { P_i1_trigger(a) } a == 5 ==> P_i1(get_next_t(t))
```
and here the second quantifier requires the first to be instantiated to prove its own well-definedness, but because of the custom trigger that is not contained in the second quantifier, does not trigger it. That's also why Malte's suggestion fixes the issue. 

I'd consider this an artifact of the QP desugaring, not a Silicon issue, so I'll close this issue.
