### ISSUE TITLE
MatchError because of VerCors-generated AST

### ISSUE THREAD

**Issue by bobismijnnaam** [viperproject/silicon#517]
For certain programs (see https://github.com/utwente-fmt/vercors/issues/456) a `MatchError` is thrown when calling Silicon with the VerCors generated AST. When the output from VerCors is given to Silicon from a text file, the `MatchError` does not occur. VerCors does not include all preprocessing passes in Viper/Silicon, which is probably why this problem does not happen in vscode for example.

The `MatchError` happens in Evaluator.scala/`eval2`. Specifically, it happens when e is of type `FieldAccessPredicate`. I've included a screenshot of a breakpoint being triggered containing some (hopefully helpful) information.

Is this a (benign?) missing case, or are we translating the expression in a wrong way? In the long term we're going to include the Viper preprocessing passes so this problem cannot happen again, but in the short term we'd like to either 1) generate the tree viper expects, or 2) make the viper internals more defensive so the tree that VerCors generates becomes okay.

For completeness, I think the problematic expression in the source file is:

```
requires (\forall* int i; true; false ? true : Perm(xs, 1\1))
```

Which I think is translated the way you would expect into a Silver AST (i.e. a forall, containing an if, which contains a `FieldAccessPredicate`, apparently). The problem seems to occur on both Silicon master and 20.07.

![image](https://user-images.githubusercontent.com/3082344/93787581-de835480-fc30-11ea-8ca0-9d8d06d51d8e.png)

The problem can be reproduced by verifying the following file with vercors, and setting a breakpoint for any thrown exception of type `MatchError` (I can provide more thorough instructions for this if needed).

`MyClass.pvl`:

```
class MyClass {
  int[] xs;

  requires (\forall* int i; true; false ? true : Perm(xs, 1\1));
  void foo();
}
```

In any case, this is not a very pressing issue, but if there is a simple change in AST generation on our side, or an extra `if` can be added in silicon to avoid this, that'd be nice.

**Comment by mschwerhoff** [comment]
Thanks for reporting this. We had similar problems before — AST caused a crash, re-parsing a pretty-printed version worked — which were typically caused by subtle bugs on our side.

Could you please post the pretty-printed Viper code that VerCors generates for the minimal `MyClass.pvl` example? Even it doesn't cause the problem, it might hint at potential root causes.

Another thing: do you check the Viper AST for [consistency ](https://github.com/viperproject/silver/blob/master/src/main/scala/viper/silver/ast/Ast.scala#L190)before passing it to Silicon? Are any errors returned?

**Comment by bobismijnnaam** [comment]
The encoded file:

```
domain frac {
  
  function frac_val(a: frac): Perm
  
  axiom frac_eq {
    (forall a: frac, b: frac :: { frac_val(a),frac_val(b) } (frac_val(a) == frac_val(b)) == (a == b))
  }
  
  axiom frac_bound {
    (forall a: frac :: { frac_val(a) } 0 / 1 < frac_val(a) && frac_val(a) <= 1 / 1)
  }
}

domain zfrac {
  
  function zfrac_val(a: zfrac): Perm
  
  axiom zfrac_eq {
    (forall a: zfrac, b: zfrac :: { zfrac_val(a),zfrac_val(b) } (zfrac_val(a) == zfrac_val(b)) == (a == b))
  }
  
  axiom zfrac_bound {
    (forall a: zfrac :: { zfrac_val(a) } 0 / 1 <= zfrac_val(a) && zfrac_val(a) <= 1 / 1)
  }
}

//  a field 
field field_MyClass_xs: Int

function new_frac(x: Perm): frac
  requires 0 / 1 < x && x <= 1 / 1
  ensures frac_val(result) == x


function new_zfrac(x: Perm): zfrac
  requires 0 / 1 <= x && x <= 1 / 1
  ensures zfrac_val(result) == x


method method_MyClass_foo(diz: Ref, current_thread_id: Int, globals: Ref)
  requires diz != null
  requires 0 <= current_thread_id
  requires (forall i: Int :: (false ? true : acc(diz.field_MyClass_xs, 1 / 1)))
{
  inhale false
}

method constructor_MyClass_MyClass(current_thread_id: Int, globals: Ref) returns (sys__result: Ref)
  requires 0 <= current_thread_id
  ensures sys__result != null
  ensures acc(sys__result.field_MyClass_xs, write) && sys__result.field_MyClass_xs == 0
{
  var diz__1: Ref
  diz__1 := new(field_MyClass_xs)
  diz__1.field_MyClass_xs := 0
  label method_end_constructor_MyClass_MyClass_0
  sys__result := diz__1
  // assert
  assert sys__result != null && (acc(sys__result.field_MyClass_xs, write) && sys__result.field_MyClass_xs == 0)
  inhale false
}
```

I think we apply about half of the consistency checks that Silicon applies but I'm not sure which or where that happens... @niomaster, can you maybe shed some light on this? (Otherwise I'll investigate)

**Comment by niomaster** [comment]
This example yields no consistency errors (Vercors does not output this, but I checked manually). I do also remember some situations in which we are crashing viper due to checks that are supposed to happen at parse time, but we directly generate the silver ast and so they do not happen, so that may be the case here.

**Comment by niomaster** [comment]
Could very well be this logic in this case: https://github.com/viperproject/silver/blob/814687d0233894172119fdc861e1d3a504496d1e/src/main/scala/viper/silver/ast/utility/QuantifiedPermissions.scala#L189-L210 normally triggered from https://github.com/viperproject/silver/blob/2dab520179a3bc02b1d61d6b39671c6187c7b4b4/src/main/scala/viper/silver/parser/Translator.scala#L411-L423

**Comment by mschwerhoff** [comment]
@niomaster Good catch. What happens if the precondition of  `method_MyClass_foo` is rewritten to `forall i: Int :: true ==> acc(diz.field_MyClass_xs, 1 / 1)`?

By the way: that precondition is equivalent to false, since it requires full permission to the same field infinitely often (for each possible integer).

For debugging purposes: it could also be helpful to run Silicon with `--logLevel ALL`. This will dump tons of information, but can help with understanding the context in which a crash occurs.

**Comment by mschwerhoff** [comment]
An unrelated question: `frac`s and `zfrac`s appear to be similar to Viper's built-in fractional permissions, so why the custom domains? The equality axioms are potentially costly because they allow a quadratic number of instantiations, due to their symmetric triggers.

**Comment by bobismijnnaam** [comment]
> why the custom domains?

Not an expert on this, but I think they are historic remnants of when we had the boogie/chalice/dafny backends. This is indeed something we should look at in the long term.

**Comment by niomaster** [comment]
> What happens if the precondition of `method_MyClass_foo` is rewritten to `forall i: Int :: true ==> acc(diz.field_MyClass_xs, 1 / 1)`?

This works fine (though I can't convince vercors to not simplify it away, so I subtituted `true` for `some_indeterminate_boolean()`)

> For debugging purposes: it could also be helpful to run Silicon with `--logLevel ALL`

Thanks for the pointer!

**Comment by mschwerhoff** [comment]
To summarise, the problem seems to be:
1. Viper's backends expects QP assertions of the shape `forall x :: c(x) ==> acc(...)`
2. VerCors creates ASTs with QP assertions of different shape
3. Viper's consistency checker does not detect these malformed assertions

If you agree, please file a new issue for [Silver](https://github.com/viperproject/silver/), reference this one from there, and close this issue.

**Comment by bobismijnnaam** [comment]
Yeah, that sounds right. I'll make an issue and close this.

In any case, we now know what we need to change in VerCors (namely, unfold if's in the short term, and move to PProgram in the long term), which was the primary reason for making this issue, so thanks for looking into this.

**Comment by mschwerhoff** [comment]
> In any case, we now know what we need to change in VerCors (namely, unfold if's in the short term, and move to PProgram in the long term), which was the primary reason for making this issue, so thanks for looking into this.

You're of course free to create `PProgram`s and have them translated to the final AST, but that's not how we intended AST creators (such as VerCors) to proceed. It would be interesting to hear why you think that this would be the better approach for you. Or similarly, what you would need in order to directly create Viper's final AST.

**Comment by niomaster** [comment]
Wytse pointed out at some point we weren't doing the consistency checks; at that point we noticed we were also missing the semantic analysis and translation and it seemed logical to want to include them as well.

For us it would be nicest if submitting a `Program` is as close as possible to submitting the equivalent silver text to viper. Of course a consistency error in this case would have helped in debugging, but in essence we still end up duplicating a translation in VerCors here. Ideally desugaring (and semantic analysis(?)) would occur over `Program` so we can take advantage of those features.

**Comment by mschwerhoff** [comment]
Thanks for the explanation. The final Viper AST is indeed meant to be exactly that, i.e. fully resolved and type-checked. If you don't want to do the latter yourself, it makes sense to generate a parse AST and let Viper do the rest for you.
