### ISSUE TITLE
Incompleteness when unfolding a predicate in a function

### ISSUE THREAD

**Issue by fpoli** [viperproject/silicon#529]
The following program fails to verify, but by uncommenting the first assert statement everything goes through. Is this a known issue? The same happens with Carbon (https://github.com/viperproject/carbon/issues/373).

```javascript
predicate P(x: Int) {
    x == 123
}

function property(x: Int): Bool
    requires P(x)
{
    unfolding P(x) in x == 123
}

method check_property(x: Int)
  requires P(x)
{
    // assert unfolding P(x) in true
    assert property(x); // Fails
}
```

**Comment by mschwerhoff** [comment]
The incompleteness is essentially by design, but the design wasn't always undisputed. In a sense, the unfolding and its effect are limited/scoped to the function body, and used to verify its well-definedness and the function's postcondition. However, the effect is not available to callees: for them, function `property`'s body is effectively `x == 123`, which explains the failing `assert` why a preceding `unfolding P(x)` avoids it.

The previously debated question was to which extent information from an unfolding should "persist" beyond function bodies. For example, would you expect the final `assert` to hold if the body of function `property` were just `unfolding P(x) in true`? From an operational point of view — calling `property(x)` executes the body, which executes the `unfolding` — the answer would probably be yes, but from an axiomatic point of view, the answer is not clear and ultimately depends on whether or not the `unfolding` is included in the function's definitional axiom (which it currently isn't).

I suggest that you turn this into a Silver issue if you'd like to discuss it in a Viper meeting.

**Comment by fpoli** [comment]
Thanks for the clarification. This matters for Prusti because we place several type invariant in the body of the predicate, and the example that I posted is a simplification of the encoding of a Rust program. I think we need to discuss this in the Prusti team before reaching the Viper team.

**Comment by fpoli** [comment]
Moved to https://github.com/viperproject/silver/issues/495
