### ISSUE TITLE
Counterexample inconsistent with Failure

### ISSUE THREAD

**Issue by dohrau** [viperproject/silicon#532]
Consider the following snippet:
```
inhale a != c ==> acc(P(c), write)

// <do stuff>

if (a != c) {
   p := perm(P(c))
}
exhale a != c ==> acc(P(c), write)
```
Assume that the code that does _the stuff_ may not preserve the permission to `P(c)` and therefore causes the exhale to fail. If we examine the counterexample corresponding to this failure, we expect the condition `a != c` to hold in it (which it does). Moreover, we also expect `p` to have a value that is less than `write` (otherwise, why would there be a failure?). However, I encountered a counterexample where `p` has the value `write` (which is inconsistent with the failure).

A possible explanation could be that the SMT query preceding the extraction of the counterexample does not contain all necessary permission-related constraints and therefore allows Z3 to pick the inconsistent value.

**Comment by marcoeilers** [comment]
I looked into Jérôme's example earlier, and the problem seems to be that counterexamples as a result of a consumeGreedy failure don't take into account the constraints related to finding the chunk to be consumed. I.e., consumeGreedy may or may not perform an SMT query, and because of that, the code generating the failures looks like this:
```
consumeGreedy(s1, s1.h, id, args, perms, v1) match {
            case (Complete(), s2, h2, optCh2) =>
              QS(s2.copy(h = s.h), h2, optCh2.map(_.snap), v1)
            case _ if v1.decider.checkSmoke() =>
              Success() // TODO: Mark branch as dead?
            case _ =>
              createFailure(ve, v1, s1, generateNewModel= true).withLoad(args)
          }
```
That is, it always asks to generate a _new_ model that _only_ takes into account the current path conditions, _not_ the assertion that there is a chunk. So one might get a model that fulfills path conditions but where one actually has the chunk being consumed, while getting an error that states that the chunk isn't there.

As far as I can see, the easiest way to avoid this would be to always use the more complete exhale, which as far as I can see always generates exactly one SMT query that we can directly use for the counterexample.

**Comment by marcoeilers** [comment]
We now require the more complete exhale option for counterexamples to avoid returning incorrect results (commit 8df301a21b7ef8a84155856551067cbeec5fc207).
