### ISSUE TITLE
Other smt solver support?

### ISSUE THREAD

**Issue by bobismijnnaam** [viperproject/silicon#540]
Are there any plans for supporting other smt solvers?

Specifically I am wondering about using CVC4, as its support for modulo arithmetic seems a bit stronger than z3's. I spend some time this morning frankensteining silicon into using CVC4 instead of Z3 (https://github.com/bobismijnnaam/silicon/tree/cvc4-support), and besides running into a crash that I think is cvc4's fault (and might even already be fixed on their master branch), and some parts of the smt2 syntax where z3 is more loose than CVC4, there don't seem to be big hurdles. Is this true, or is silicon using some z3 specific features that are non-trivial to port to CVC4?

Boogie already has experimental cvc4 support, would it be easy to have a flag that enables it in carbon?

Finally, silicon currently uses a lot of z3 specific options, for performance tuning and reproducibility, I suppose. Would it be an idea to have a solver-agnostic mode (which I think would only require leaving out the z3 specific options)? Then using a new smt solver would be almost trivial. Of course there'd be no guarantees about reproducibility and performance, but it'd be very nice to have some options for prototyping once z3 starts getting stuck on a problem. Maybe some frontends could even use different solvers for different proof goals? Having a solver-agnostic mode also makes it easier for silicon to stick to non-loose smt2 syntax, as it would be easy to plug in another prover and check if no syntax errors occur.

**Comment by mschwerhoff** [comment]
We don't have concrete plans, but also don't see fundamental reasons against supporting other SMT solvers. We experimented with CVC a few years ago, but back then, 1. CVC ignored quantifier patterns, which resulted in poor performance, and 2. many Z3 features (used by Silicon) weren't part of SMTLIB. Both has changed since then, however, and another experiment would be interesting. We'll keep an eye out for a student interested in working on this.

Regarding your Silicon fork: We're generally open to external contributions, and if you consider the fork good enough, I 'd be happy to review a pull request, and running performance benchmarks (and asking frontend developers from our group to benchmark their frontends). Ideally, adding the option to use CVC does not affect the performance when using Z3.

Regarding "different solvers different proof goals": keep in mind that the proof goal might look non-complex, e.g. x != y, but that answering the query may require arbitrary theories, depending on the solver's current assertion stack (path conditions). The [Jahob verifier](https://lara.epfl.ch/w/jahob_system) explored an approach where different solvers were used to handle different subsets of the involved path conditions, but — to my impression — with limited success.

**Comment by mschwerhoff** [comment]
Regarding Carbon: You can already forward options to Boogie; maybe that suffices to experiment with CVC via Carbon.

**Comment by bobismijnnaam** [comment]
Thanks for the reply. I'll experiment with the forwarding of boogie options, that sounds like the best short term option.

**Comment by bobismijnnaam** [comment]
I tried telling boogie to use cvc4 using the following invocation:

```
$ ./bin/carbon --boogieOpt "/proverOpt:SOLVER=CVC4" temp.sil
```

But got a big stack trace from boogie about a broken pipe... So no easy solutions unfortunately.

**Comment by mschwerhoff** [comment]
Progress has been made: https://github.com/viperproject/silicon/pull/609

Should be merged in soon.

**Comment by marcoeilers** [comment]
Since we now have support for CVC5, I'll close this issue.
