### ISSUE TITLE
NPE in Z3ProverStdIO

### ISSUE THREAD

**Issue by jcp19** [viperproject/silicon#544]
The current implementation of `readLine` in the class `Z3ProverStdIO` is not prepared to handle the case where `input.readLine()` returns null in the first statement of the loop. This leads to a Null Pointer Exception when that occurs.

```scala
  private def readLine(): String = {
    var repeat = true
    var result = ""

    while (repeat) {
      result = input.readLine()
      if (result.toLowerCase != "success") comment(result)

      val warning = result.startsWith("WARNING")
      if (warning) {
        val msg = s"Z3 warning: $result"
        reporter report InternalWarningMessage(msg)
        logger warn msg
      }

      repeat = warning
    }

    result
  }
```

PS: the readLine function called in `input.readLine()` returns null if the end of the stream has been reached without reading any characters, accordig to the documentation.

**Comment by mschwerhoff** [comment]
Thanks for reporting this. It is unclear to me, though, what an appropriate reaction to `input.readLine() == null` would be. I.e. what should be reported to the user? E.g. if it can only occur if an exceptional problem in the communication with Z3 arose, then we can probably only report exactly that. Otherwise, we could maybe report a more helpful message.

**Comment by jcp19** [comment]
It is a bit hard to chose a particular solution for this problem indeed. I will look more into it. At first, my idea was that there could be some sort of race condition between silicon and z3, where silicon could be trying to read from the stdin before z3 published the results in its stdout. Maybe this does not make sense, I am not super familiar with silicon's codebase yet. However, if that is indeed the case, then the "best" fix would be to try again to call `readLine`

**Comment by mschwerhoff** [comment]
In this past, the underlying problem usually was a nondeterministically occurring segfault in Z3, with the nondeterminism due to timeouts in the generated SMT code. Reproducing the problem is difficult, but once you're reasonably sure ("usually happens one out of 100 runs"), you can report them on the Z3 issue tracker.

To investigate such a Z3 issue, I recommend the following steps:

1. Repeatedly run `silicon --numberOfParallelVerifiers 1` on the problematic Viper file, until it crashes
1. Once that happened (or you lost patience), you can take the generated `tmp/logfile-01.smt2` and move on to Z3
1. Get a debug build of Z3, as [described here][1] or (for Windows) [from Jenkins][2]
1. Repeatedly run Z3 on the SMT file, maybe with varying random seeds. It sometimes took me tens of thousands of runs to observe a nondeterministic segfault ... If you're fortunate, one of the debug build's many asserts is hit, in which case you'll even get line and file information.
1.  Once you're fairly sure that you found a problem, you can report it on the Z3 issue tracker — even if "reproducing" it means running Z3 a thousand times and crossing your fingers

A potential further complication: If you uncover a bug in an older Z3 version, it's best to try to uncover it in the latest Z3 revision as well, to increase the developer's motivation to look into it.

[1]: <https://github.com/viperproject/internal/wiki/Compiling-Z3>
[2]: <https://pmbuilds.inf.ethz.ch/job/z3-latest-debug/>

**Comment by jcp19** [comment]
Thanks @mschwerhoff! I will do that

**Comment by mschwerhoff** [comment]
@jcp19 Did you find any time to look further into this? 

Since `input.readLine()` should not return null (assuming Z3 runs fine), I'd fix this by throwing some kind of "Unexpected Z3 behaviour" exception. Let me know if you have a better idea.

**Comment by jcp19** [comment]
@mschwerhoff unfortunately more important tasks came up and I ended up forgetting about this. I think that the solution of throwing an exception makes a lot of sense - an alternative with similar flavor would be to introduce a new kind of verification error. I don't know the architecture of ViperServer by heart but maybe the latter solution would avoid crashing the entire server and to visualize the error message in the IDE.

**Comment by mschwerhoff** [comment]
As of commit 9a416fec44f7138f3dd80b85bf7ed3c7fa89854b, an exception will be raised if reading from Z3's stdout returned `null`.
