### ISSUE TITLE
Unfolding seems to be missing when asserting function

### ISSUE THREAD

**Issue by bobismijnnaam** [viperproject/silicon#873]
In the following program, the assert fails, where I would expect it to hold:

```
field x: Int

predicate p(c: Ref) {
  acc(c.x, write) && c.x == 0
}

function foo(c: Ref): Bool
  requires acc(p(c), write)
{
  (unfolding acc(p(c), write) in c.x == 0)
}

method chor_run1(tid: Int, a: Ref) returns (res: Int)
  requires a != null
  requires acc(p(a), write)
{
  // assert (unfolding acc(p(a), wildcard) in a.x == 0)
  // assert (unfolding acc(p(a), wildcard) in foo(a))
  assert foo(a)
}
```

If either of the two asserts is uncommented, the file verifies. It seems that the predicate `p` is not unfolded when `foo` is named, is that a bug or a limit of the implementation? Carbon also does not verify it.

**Comment by bobismijnnaam** [comment]
Probably a duplicate of https://github.com/viperproject/silver/issues/495, is that correct? Feel free to close the issue if so.

**Comment by viper-admin** [comment]
Yeah that looks like it's exactly the same situation, and it's apparently by design. This is definitely sometimes useful in practice because it essentially makes it possible to hide irrelevant information from a complex predicate by moving the unfolding to a function. 
FWIW, you can of course "forward" information from the unfolding to the function call site by adding it to the function's postcondition.

**Comment by jcp19** [comment]
I wonder if this design choice is still reasonable given that we now have `opaque` functions. With this, devs can be explicit about when they want to hide implementation details of a function, instead of having this arguably surprising behaviour.
